# Generated by Django 4.0.3 on 2022-03-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
    ]
